title = 'DreamCraft Docs'
description = 'DreamCraft Docs'
evergreen = true
base = './'


[locales]
'/' = { lang = 'zh-CN', title = 'DreamCraft 用户手册' }
'/en/' = { lang = 'en-US', title = 'DreamCraft Docs' }

[themeConfig]
repo = 'DreamCraft-Tech/DreamCraft-Docs'
docsBranch = 'master'
docsDir = 'src'
editLinks = true

[themeConfig.locales.'/']
selectText = '选择语言'
label = '简体中文'
docsDir = 'src'
editLinkText = '在 Github 上提交更改'
lastUpdated = '最后更新'

[themeConfig.locales.'/en/']
selectText = 'Language'
label = 'English'
docsDir = 'src/en'
editLinkText = 'Commit Changes on Github'
lastUpdated = 'Last updated on'

[[themeConfig.locales.'/'.nav]]
text = 'Web Service'
link = '/'
[[themeConfig.locales.'/'.nav]]
text = 'Launcher'
link = '/launcher/'
[[themeConfig.locales.'/'.nav]]
text = 'Mirrors'
link = '/mirrors/'

[themeConfig.locales.'/'.sidebar] # 侧边栏导航
'/mirrors/' = [
    '/mirrors/introduction',
]
'/launcher/' = [
    '/launcher/introduction',
]
'/' = [
    '/introduction',
]
# 根导航必须写在最后