name: 自动部署至Gitee

on:
  push:
  workflow_dispatch:
  schedule: # 计划任务触发
    - cron: '0 16 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 自动部署至Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:DreamCraft-Tech/DreamCraft-Docs.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:DreamCraft-Tech/DreamCraft-Docs.git
